#!/bin/sh

## Compile
export CCACHE_DIR="/home/sultan/.ccache_kernel"
export ARCH=arm
export CROSS_COMPILE=/home/sultan/sultan-projects/arm-eabi-4.7/bin/arm-eabi-
make -j100 ARCH=arm

## Compress ramdisk
./scripts/mkbootfs ramdisk/ | gzip > ramdisk.gz

## Assemble boot.img
./scripts/mkbootimg --kernel arch/arm/boot/zImage --cmdline 'androidboot.hardware=qcom usb_id_pin_rework=true no_console_suspend=true' --base 0x40400000 --ramdisk_offset 0x01400000 --pagesize 2048 --ramdisk ramdisk.gz --output boot.img

## Compress all modules & boot.img into zips
mkdir modules
cp -a $(find . -name *.ko -print |grep -v initramfs) modules
zip modules.zip modules/*
zip boot.img.zip boot.img

## Clean up
rm -r -f modules/
rm -f ramdisk.gz
